{% set name = "yaqd-labjack" %}
{% set version = "2023.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 89577fb25305296fb561a92a9658d9ff951f8e125d4d5e45edce45b80185cc7d

build:
  entry_points:
    - yaqd-labjack-sensor = yaqd_labjack._labjack_sensor:LabjackSensor.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - pyserial-asyncio
    - pymodbus >=3
    - python >={{ python_min }}
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_labjack
  commands:
    - yaqd-labjack-sensor --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq daemons for LabJack measurement devices
  dev_url: https://github.com/yaq-project/yaqd-labjack
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
