{% set name = "yaqd-labjack" %}
{% set version = "2023.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-labjack-{{ version }}.tar.gz
  sha256: 584cf48508f7e73b45704d4d00cba0cd66bc9b5093dca1e1c2b2054d93542cf3

build:
  entry_points:
    - yaqd-labjack-sensor = yaqd_labjack._labjack_sensor:LabjackSensor.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - pymodbus
    - python >=3.7
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_labjack
  commands:
    - pip check
    - yaqd-labjack-sensor --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for LabJack measurement devices
  dev_url: https://github.com/yaq-project/yaqd-labjack
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
